route/urls.py
from django.conf.urls import patterns, url, include
from django.views.decorators.csrf import csrf_exempt


urlpatterns = patterns('route.views',
    url(r'^$', 'index', name="index"),
    url(r'^admin-view/', 'admin_view', name="admin-view"),
    url(r'^add-route/$', 'add_route', name="add-route"),
    url(r'^manage-route/$', 'manage_route', name="manage-route"),
)

urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView
from django.conf.urls.i18n import i18n_patterns

from users.views import login_to_application

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', 'index', name="route-index"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^route/', include('route.urls', namespace='route')),
)

# users app
urlpatterns += patterns('',
    url(r'^login/$', login_to_application),
)

route/models.py
from django.contrib.gis.db import models

class route(models.Model):
    route_name = models.CharField(max_length=50)
    start_point = models.PointField()
    end_point = models.PointField()
    route_points = models.GeometryField()
    destination = models.TextField()
    objects = models.GeoManager()

    def __unicode__(self):
        return "%r" % self.route_name

users/models.py
from django.contrib.auth.models import User
from django.contrib.auth.models import UserManager
from django.db import models
# from uuid import uuid4
# from time import strftime
# import os

GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

class AppUser(User):
    """
        Create a new user of the application.
    """

    # def get_upload_path(instance, filename):
    #     fname, dot, extension = filename.rpartition('.')
    #     new_name = '%s.%s' % (str(uuid4().hex), extension)
    #     return os.path.join("images", "avatars", "%s/%s/%s" % (strftime("%Y"), strftime("%m"), strftime("%d")), new_name

    # avatar = models.ImageField("Display Picture", upload_to=get_upload_path, null=True, blank=True)
    birthdate = models.DateField(blank=True, null=True)
    gender= models.CharField(max_length = 10, blank=True, choices=GENDER_CHOICES)

    def __unicode__(self):
        return self.username

route/views.py
import os
import json
import logging
import settings
import json
import urlparse
import HTMLParser
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.core.urlresolvers import reverse
from route import models
from django.contrib.gis.geos import Point, LineString

def index(request, template='route/index.html'):
    context = {}
    if request.method == "GET":
        context['routes'] = models.route.objects.all()
    return render_to_response(template, context, RequestContext(request))

def admin_view(request, template='route/admin-view.html'):
    context = {}
    return render_to_response(template, context, RequestContext(request))

def manage_route(request, template='route/manage_route.html'):
    context = {}

    if request.method == "GET":
        context['routes'] = models.route.objects.all()
    elif request.method == "POST" and request.is_ajax():
        route_n = request.POST.get('route_name')
        route_d = request.POST.get('route_destination')
        points = request.POST.getlist('points[]')

        p1 = points[0].find(',')
        np1 = Point(float(points[0][0:p1]),float(points[0][p1+1:]))

        p2 = points[len(points)-1].find(',')
        np2 = Point(float(points[len(points)-1][0:p1]),float(points[len(points)-1][p2+1:]))

        route_points = []
        i = 0

        for pp in points:
            c1 = points[i].find(',')
            cp1 = (float(points[i][0:c1]),float(points[i][c1+1:]))
            route_points.append(cp1)
            i = i + 1

        rout = LineString(route_points)

        #nroute = models.route(route_name = route_n, destination = route_d)
        #nroute.start_point = np1
        #nroute.end_point = np2
        #nroute.route_points = rout
       # nroute.save()

    return render_to_response(template, context, RequestContext(request))


def add_route(request, template='route/add_route.html'):
    context = {}

    if request.method == "POST" and request.is_ajax():
        route_n = request.POST.get('route_name')
        route_d = request.POST.get('route_destination')
        points = request.POST.getlist('points[]')

        p1 = points[0].find(',')
        np1 = Point(float(points[0][0:p1]),float(points[0][p1+1:]))

        p2 = points[len(points)-1].find(',')
        np2 = Point(float(points[len(points)-1][0:p2]),float(points[len(points)-1][p2+1:]))

        route_points = []
        i = 0

        for pp in points:
            c1 = points[i].find(',')
            cp1 = (float(points[i][0:c1]),float(points[i][c1+1:]))
            route_points.append(cp1)
            i = i + 1

        rout = LineString(route_points)

        nroute = models.route(route_name = route_n, destination = route_d)
        nroute.start_point = np1
        nroute.end_point = np2
        nroute.route_points = rout
        nroute.save()

    return render_to_response(template, context, RequestContext(request))

users/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext

def login_to_application(request, template='users/login.html'):
    context = {}
    return render_to_response(template, context, context_instance=RequestContext(request))

templates/base.html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %} | The Open Route Project</title>

  <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/cupertino/jquery-ui.css" type="text/css" media="all" />
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />
  <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/route.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/sticky-footer.css">
  <!-- 
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js"></script>
   -->
  <script src="{{ STATIC_URL }}js/jquery-1.9.1.js"></script>
  <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script> 
  <script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="http://beta.mapquestapi.com/sdk/leaflet/v0.1/mq-map.js?key=Fmjtd%7Cluur290125%2Caa%3Do5-90zx0y "></script>
  <script src="http://beta.mapquestapi.com/sdk/leaflet/v0.1/mq-routing.js?key=Fmjtd%7Cluur290125%2Caa%3Do5-90zx0y "></script>
  <script src="http://www.mapquestapi.com/sdk/js/v7.0.s/mqa.toolkit.js?key=Fmjtd%7Cluur290125%2Caa%3Do5-90zx0y "></script>

  {% block extra_child_items %}{% endblock extra_child_items %}
  {% block extra_meta %}{% endblock extra_meta %}
  {% block extra_css_top %}{% endblock extra_css_top %}
  {% block extra_js_top %}{% endblock extra_js_top %}
</head>

<body>
  <div id="wrap">
    <header class="navbar" role="navigation">
      {% block header %}
      {% endblock header %}
    </header>

    {% block sub_header %}
    {% endblock sub_header %}

    <div class="container">
      {% block main %}
      {% endblock main %}
    </div>
  </div><!-- /#wrap -->

  <footer>
    {% block footer %}
    {% endblock footer %}
  </footer>

  {% block extra_css_bottom %}{% endblock extra_css_bottom %}
  {% block extra_js_bottom %}{% endblock extra_js_bottom%}
</body>
</html>

templates/index_with_footer.html
{% extends "base.html" %} 

{% block extra_child_items %}
  <link rel="stylesheet" href="{{ STATIC_URL }}css/index.css">
{% endblock extra_child_items %}

{% block header %}
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand">Open Route</a>
    </div>

    <div class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-left">
        {% block header_items_left %}
        {% endblock header_items_left %}
      </ul>

      {% block header_items_right %}
      {% endblock header_items_right %}
    </div>
  </div><!-- /.container -->
{% endblock header %}

{% block sub_header %}
  <div class="sub-header">
    <div class="container">
      <div class="sub-header-title">
        {% block sub_header_title %}
        {% endblock sub_header_title %}
      </div>
    </div>
  </div>
{% endblock sub_header %}

{% block footer %}
  <div class="container">
    <p>Copyright &copy; 2013&ndash;2014 <a href="#">The Open Route Project</a>. All rights reserved.</p>
  </div>
{% endblock footer %}

templates/main_with_map.html
{% extends "mobile-base.html" %} 

{% block subpage_extras %}
  {% block extra_meta %}
  {% endblock extra_meta %}
  
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />
  <!-- <link rel="stylesheet" href="{{ STATIC_URL }}css/route.css"> -->
  <link rel="stylesheet" href="{{ STATIC_URL }}css/main_with_map.css">
  {% block extra_css_top %}
  {% endblock extra_css_top %}

  <script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>
  <script src="{{ STATIC_URL }}js/current_location.js"></script>
  <script src="http://beta.mapquestapi.com/sdk/leaflet/v0.1/mq-map.js?key=Fmjtd%7Cluur290125%2Caa%3Do5-90zx0y "></script>
  <script src="http://beta.mapquestapi.com/sdk/leaflet/v0.1/mq-routing.js?key=Fmjtd%7Cluur290125%2Caa%3Do5-90zx0y "></script>
  <script src="http://www.mapquestapi.com/sdk/js/v7.0.s/mqa.toolkit.js?key=Fmjtd%7Cluur290125%2Caa%3Do5-90zx0y "></script>
  {% block extra_js_top %}
  {% endblock extra_js_top %}
{% endblock subpage_extras %}

{% block main_header %}
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">
        <img class="site-logo" src="{{ STATIC_URL }}img/open-route-logo-small.png" alt="The Open Route Project">
      </a>
    </div>
  </div><!-- /.container -->
{% endblock main_header %}

{% block footer %}
  <div class="copyright">
    <div class="container">
      <p>Copyright &copy; 2013&ndash;2014 <a href="/">The Open Route Project</a>. All rights reserved.</p>
    </div>
  </div>
{% endblock footer %}

templates/mobile-base.html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %} | The Open Route Project</title>

  <link rel="icon" href="{{ STATIC_URL }}img/favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/cupertino/jquery-ui.css" type="text/css" media="all" />
  <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/font-awesome.min.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/sticky-footer.css">

  <script src="{{ STATIC_URL }}js/jquery-1.9.1.js"></script>
  <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script> 

  {% block subpage_extras %}{% endblock subpage_extras %}
</head>
<body>
  <div id="wrap">
    <header class="navbar" role="navigation">
    {% block main_header %}
    {% endblock main_header %}
    </header>

    {% block sub_header %}
    {% endblock sub_header %}

    {% block side_panel %}
    {% endblock side_panel %}

    {% block main_content %}
    {% endblock main_content %}

  </div><!-- /#wrap -->

  <footer>
  {% block menu_panel %}{% endblock menu_panel %}
  {% block footer %}{% endblock footer %}
  </footer>

  {% block extra_css_bottom %}{% endblock extra_css_bottom %}
  {% block extra_js_bottom %}{% endblock extra_js_bottom %}
</body>
</html>

templates/route/add_route.html
{% extends "index_with_footer.html" %}

{% block extra_css_top %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/route/map.css">
{% endblock extra_css_top %}

{% block extra_js_top %}
  <script type="text/javascript">

   var map;
   var marker;
   var dir = MQ.routing.directions();
   var points = [];

    function onMapDblClick(event) {
     // alert("You clicked the map at " + e.latlng);
      //marker = L.marker(e.latlng, {draggable:'true'} ).addTo(map);
      //marker.on('click', onMarkerClick);
      //points.push([e.latlng.lat,e.latlng.lng]);
      var lat = event.ll.getLatitude();
      var lng = event.ll.getLongitude();
      addNewRoute(lat,lng);
      updateRoutes();
    }

    function addNewRoute(lat,lng){
      points.push([lat,lng]);
    }

    
   $(document).ready(function() {

     points.push([7.09359 ,125.60841]);
     points.push([7.16356,125.60845]);
     points.push([7.17356,125.60945]);
     

     getMap();
     updateRoutes();
     MQA.withModule('largezoom','viewoptions','geolocationcontrol','insetmapcontrol','mousewheel', function() {
           map.addControl(
             new MQA.LargeZoom(),
             new MQA.MapCornerPlacement(MQA.MapCorner.TOP_LEFT, new MQA.Size(5,5))
           );
         
            var options={
             size: { width: 150, height: 125 },
             zoom: 3,
             mapType: 'osmsat',
             minimized: false
           };
         
           map.addControl(
             new MQA.InsetMapControl(options),
             new MQA.MapCornerPlacement(MQA.MapCorner.BOTTOM_RIGHT)
           );
         
           map.enableMouseWheelZoom();
         });
      
     });

     function updateRoutes(){
      var locations = new Array(points.length);
       for(i = 0; i <points.length ; i++){
            locations.push({latLng: {lat: points[i][0], lng: points[i][1]}})
        }
        MQA.withModule('directions', function() {
        map.addRoute(locations, {ribbonOptions:{draggable:true, draggablepoi:true}});
       });
    }
    
     function getMap() {
        var options={
           elt: document.getElementById('map'),        
           zoom: 13,                              
           latLng: {lat:7.06359, lng: 125.60841},   
           mtype: 'osm',                             
           bestFitMargin: 0,             
           zoomOnDoubleClick: false                   
         };
        
        window.map = new MQA.TileMap(options); 
        MQA.EventManager.addListener(map, 'doubleclick', onMapDblClick);
     }
   

    

 </script>
{% endblock extra_js_top %}

{% block main %}
  <div id="map"></div>

<div> 
<p>Routes: </p>

<form method="POST">
  {% csrf_token %}
Route Name: <input type="text" name="route_name" value="" id="route_name" size="20" /></br> 
<button type="submit" name="save">Save new route</button>
</form>
</div>
{% endblock main %}

templates/route/admin-view.html
{% extends "index_with_footer.html" %}
 

{% block title %}Sample Route{% endblock title %}

{% block main %}

<a href="{% url 'route:add-route' %}" class="route">Add new route</a><br>
<a href="{% url 'route:manage-route' %}" class="route">Edit/Delete routes</a>

{% endblock main %}

templates/route/index.html
{% extends "main_with_map.html" %}

{% block title %}View Sample Route{% endblock title %}

{% block extra_css_top %}
{% endblock extra_css_top %}

{% block extra_js_top %}
  <script type="text/javascript">
    $(document).ready(function() {
      getMap();
      MQA.withModule('largezoom','viewoptions','geolocationcontrol','insetmapcontrol','mousewheel',
        function() {
          map.addControl(
            new MQA.LargeZoom(),
            new MQA.MapCornerPlacement(MQA.MapCorner.TOP_LEFT, new MQA.Size(5,5))
          );
          map.enableMouseWheelZoom();
        });
      });

       window.toggleSearch = function() {
        $("#search-group").toggle();
        }

      function getMap() {
        var options = {
           elt: document.getElementById('map'),
           zoom: 13,
           latLng: {lat:7.06359, lng: 125.60841},
           mtype: 'osm',
           bestFitMargin: 0,
           zoomOnDoubleClick: false
         };
        
      window.map = new MQA.TileMap(options);
    }

    function enterSearch(e) {
      if (e.keyCode == 13) {
       alert('w');
      }
    }
  </script>
{% endblock extra_js_top %}

{% block main_content %}
<div id="map" class="page-map" style="min-height: 500px;">
</div>
{% endblock main_content %}

{% block menu_panel %}
<div class="menu-panel">
  <div class="container">
    <div class="form-group" id="search-group" style="display: none;">
      <input type="text" class="form-control" placeholder="Search" onkeypress="return enterSearch(event)">
    </div>
    <div class="btn-group btn-group-justified">
      <div class="btn-group">
        <a href="#" class="btn btn-lg btn-menu-panel" title="Search" onclick="window.toggleSearch()">
          <i class="fa fa-search"></i>
          <span class="visible-xs"> Search</span>
        </a>
      </div>
      <div class="btn-group">
        <a href="#" class="btn btn-lg btn-menu-panel" title="Current Location" onclick="getCurrentLocation()">
          <i class="fa fa-dot-circle-o"></i>
          <span class="visible-xs"> Current Location</span>
        </a>
      </div>
      <div class="btn-group">
        <a href="#" class="btn btn-lg btn-menu-panel" title1="Refresh">
          <i class="fa fa-refresh"></i>
          <span class="visible-xs"> Refresh</span>
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock menu_panel %}

templates/route/manage_route.html
{% extends "index_with_footer.html" %}


{% block extra_css_top %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/route/route.css">
{% endblock extra_css_top %}

{% block extra_js_top %}
  <script type="text/javascript">

   var map;
   var marker;
   var points = [];
   var dictRoutes = [];

    //on map load
    $(document).ready(function() {     
     getMap();

    $("#allroutes tr").click(function(e){
      var data = [];
      var target = e.srcElement || e.target;
      var cells = target.getElementsByTagName("td");
      while (target && target.nodeName !== "TR") {
        target = target.parentNode;
      }
      if (target) {
          var cells = target.getElementsByTagName("td");
          for (var i = 0; i < cells.length; i++) {
              data.push(cells[i].innerHTML);
          }
      }

     points = [];
     convertStringToArray(data[3].trim());
     if (points.length >= 2 ){ 
                updateRoutes();
      }

      $("#route_name").val(data[1].trim());
      $("#route_destination").val(data[2].trim());
    });

     var frm = $('#form1');
      frm.submit(function () {
        var route_name = $('#route_name').val();
        var route_destination = $('#route_destination').val();

        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: {csrfmiddlewaretoken: "{{ csrf_token }}",'points[]': points,'route_name' : route_name, 'route_destination' : route_destination },
            success: function (data) {
                window.location.reload(true);
            }
        });
        return false;
      });
    });

    function convertStringToArray(inp){
      var tup1="", tup2="";
      var check=0;
      var comcheck=0;
      console.log(inp);
      for(var i=0;i<inp.length-1;i++){
          if(inp.charAt(i) == '('){
            continue;
          }
          else if(inp.charAt(i) == ',' && comcheck == 0){
              check = 1;
              comcheck = 1;
              continue;
          }
          else if(inp.charAt(i) == ',' && comcheck == 1){
            comcheck = 0;
            continue;
          }
          else if(inp.charAt(i) == ')'){
            check=0;
            addNewRoute(parseFloat(tup1.trim()),parseFloat(tup2.trim()));
            tup1 = "";
            tup2 = "";
            continue;
          }

          if(check == 0 && typeof inp.charAt(i) != "undefined"){
            tup1 = tup1 + inp.charAt(i);
          }
          else if(check == 1 && typeof inp.charAt(i) != "undefined"){
            tup2 = tup2 + inp.charAt(i);
          }
      }
    }

    function onMapDblClick(event) {
      var lat = event.ll.getLatitude();
      var lng = event.ll.getLongitude();
      addNewRoute(lat,lng);
      alert("Added new route point!");

      if (points.length >= 2 ){ 
        updateRoutes();
      }
    }


    function addNewRoute(lat,lng){
      console.log("lat:" + lat + "lng:" + lng);
        points.push([lat,lng]);
    }

    function clearRoutes(){
      points = []
      window.map.dispose();
      getMap();
    }
    
     function updateRoutes(){
      var locations = new Array(points.length);
         for(i = 0; i <points.length ; i++){
              locations.push({latLng: {lat: points[i][0], lng: points[i][1]}})
          }
          
      MQA.withModule('directions', function() {
          map.addRoute(locations, {ribbonOptions:{draggable:true, draggablepoi:true}});
         });
    }
    
     function getMap() {
        var options={
           elt: document.getElementById('map'),        
           zoom: 13,                              
           latLng: {lat:7.06359, lng: 125.60841},   
           mtype: 'osm',                             
           bestFitMargin: 0,             
           zoomOnDoubleClick: false                   
         };
        
        window.map = new MQA.TileMap(options); 

        MQA.withModule('largezoom','viewoptions','geolocationcontrol','insetmapcontrol','mousewheel', function() {
           map.addControl(
             new MQA.LargeZoom(),
             new MQA.MapCornerPlacement(MQA.MapCorner.TOP_LEFT, new MQA.Size(5,5))
           );
         
            /* var options={
             size: { width: 150, height: 125 },
             zoom: 3,
             mapType: 'osmsat',
             minimized: false
           };
         
           map.addControl(
             new MQA.InsetMapControl(options),
             new MQA.MapCornerPlacement(MQA.MapCorner.BOTTOM_RIGHT)
           ); */
         
           map.enableMouseWheelZoom();
         });

        MQA.EventManager.addListener(map, 'doubleclick', onMapDblClick);
     }
     
 </script>
{% endblock extra_js_top %}

{% block main %}
  <div id="map"></div>

<div id="testdiv"> 
<p>Routes: </p>
<button type="submit" name="clear" onclick="clearRoutes()">Clear Route Points</button>
<form method="POST" id="form1">
  {% csrf_token %}
  Route Name: <input type="text" name="route_name" value="" id="route_name" size="20" /></br> 
  Destination : <textarea rows="4" cols="50" name="route_destination" id="route_destination" placeholder="place, place"></textarea></br> 
  <button type="submit" name="save">Save new route</button>
  </br>  </br> 
</form>
<p>All Routes: </p>
  <table name="allroutes" id="allroutes">
  <th>Route ID</th>
  <th>Route Name</th>
  <th>Destination</th>
  <th>Route Points</th>
        {% for route in routes %}
        <tr id="indvroutes">
            <td>
                {{ route.id }}
            </td>
            <td>
                {{ route.route_name }}
            </td>
            <td>
                {{ route.destination }}
            </td>
            <td>
                {{ route.route_points.coords }}
            </td>
        </tr> 
        {% endfor %}  
  </table>
</div>
{% endblock main %}

templates/users/login.html
{% extends "index_with_footer.html" %} 

{% block title %}Sign up{% endblock title %}

{% block sub_header_title %}
Login
{% endblock sub_header_title %}

{% block main %}
<div class="row">
  <!-- Login -->
  <div class="col-md-6">
    <form id="login" role="form">
      <div class="form-group">
        <input type="email" class="form-control" id="loginEmail" placeholder="Email Address" />
      </div>
      <div class="form-group">
        <input type="password" class="form-control" id="loginPassword" placeholder="Password" />
      </div>
      <div class="checkbox">
        <label>
          <input type="checkbox" value="">
          Remember me
        </label>
      </div>
      <button id="signupButton" type="submit" class="btn btn-default">Login</button>
    </form>

  </div>
  <!-- Sign Up -->
  <div class="col-md-6">
    <form id="signup" role="form">
      <div class="form-group">
        <input type="text" class="form-control" id="signupLastName" placeholder="Last Name" />
      </div>
      <div class="form-group">
        <input type="text" class="form-control" id="signupFirstName" placeholder="First Name" />
      </div>
      <div class="form-group">
        <input type="email" class="form-control" id="signupEmail" placeholder="Enter email" />
      </div>
      <div class="form-group">
        <input type="password" class="form-control" id="signupPassword1" placeholder="New Password" />
      </div>
      <div class="form-group">
        <input type="password" class="form-control" id="signupPassword2" placeholder="Confirm Password" />
      </div>
      <div class="form-group">
        <input type="date" class="form-control" id="signupBirthdate" />
      </div>
      <select id="signupGender" class="form-control">
        <option>Male</option>
        <option>Female</option>
      </select>
      <br />
      <button id="signupButton" type="submit" class="btn btn-success">Sign Up</button>
    </form>
  </div>
</div>
{% endblock main %}